# Generated by Django 6.0.2 on 2026-02-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.TextField(verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde')),
                ('type_compte', models.CharField(choices=[('EPARGNE', 'Compte Épargne'), ('COURANT', 'Compte Courant'), ('PAYANT', 'Compte Payant')], max_length=10, verbose_name='Type de compte')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='banque.agence')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='CompteCourant',
            fields=[
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='courant_details', serialize=False, to='banque.compte')),
                ('decouvert', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Découvert autorisé')),
            ],
            options={
                'verbose_name': 'Détails Compte Courant',
                'verbose_name_plural': 'Détails Comptes Courant',
            },
        ),
        migrations.CreateModel(
            name='CompteEpargne',
            fields=[
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='epargne_details', serialize=False, to='banque.compte')),
                ('taux_interet', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name="Taux d'intérêt (%)")),
            ],
            options={
                'verbose_name': 'Détails Compte Épargne',
                'verbose_name_plural': 'Détails Comptes Épargne',
            },
        ),
        migrations.CreateModel(
            name='ComptePayant',
            fields=[
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payant_details', serialize=False, to='banque.compte')),
            ],
            options={
                'verbose_name': 'Détails Compte Payant',
                'verbose_name_plural': 'Détails Comptes Payant',
            },
        ),
        migrations.AddField(
            model_name='compte',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='banque.client'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('VIREMENT_ENVOYE', 'Virement envoyé'), ('VIREMENT_RECU', 'Virement reçu'), ('CALCUL_INTERET', 'Calcul intérêt'), ('FRAIS', 'Frais')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde après')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='banque.compte')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date'],
            },
        ),
    ]
